[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LowLevelParticleFilters = "d9d29d28-c116-5dba-9239-57a5fe23875b"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Particles = "8b319fde-cee8-4296-be82-a4dd2761f2fc"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticDistributions = "6b425a2e-5cc7-4b1a-83a8-1af27c3a052c"
